'use client'

import { ArrowDownToLine, ArrowRight, FileCode2, FileText, Layers3, Upload } from 'lucide-react'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Field, FieldLabel } from '@/components/ui/field'
import { disclaimer, downloadReport, scenes, taskNames, type Mode, type Result } from '@/lib/satquery-simulation'
import type { LocalImage } from './viewer'

export type DialogView = 'about' | 'scenes' | 'upload' | 'history' | 'export' | null
export function WorkspaceDialogs({ view, setView, sceneId, onScene, result, history, onRestore, mode, uploads, onUpload, uploadError, uploading }: { view: DialogView; setView: (v: DialogView) => void; sceneId: string; onScene: (id: string) => void; result: Result | null; history: Result[]; onRestore: (r: Result) => void; mode: Mode; uploads: (LocalImage | null)[]; onUpload: (file: File, slot: number) => void; uploadError: string; uploading: boolean }) {
  const titles = { about: 'Built for a different perspective.', scenes: 'Explore a sample scene', upload: 'Bring your own imagery', history: 'Recent analyses', export: 'Export your analysis' }
  return <Dialog open={view !== null} onOpenChange={open => { if (!open) setView(null) }}><DialogContent className="sm:max-w-xl max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>{view ? titles[view] : ''}</DialogTitle><DialogDescription>{view === 'about' ? 'SatQuery AI · Smart India Hackathon · SIH26167' : view === 'scenes' ? 'Generated satellite-style examples. Not real acquisitions.' : view === 'upload' ? 'Local preview only. Images never leave your browser and are not analyzed.' : view === 'history' ? 'Sample-scene analyses from this session. Refreshing clears these records. Upload previews are not retained.' : 'A transparent record of your illustrative result and execution trace.'}</DialogDescription></DialogHeader>
    {view === 'about' && <div className="about-content"><p>A vision-language workspace inspired by the supplied SIH26167 guide. Ask questions about remote-sensing imagery and explore how specialized capabilities work together.</p><div className="architecture">{['Input & preprocessing', 'Query understanding', 'Agentic controller', 'Specialist models', 'Evidence & response'].map((label, i) => <div key={label}><span className="architecture-number">0{i + 1}</span><span>{label}</span><Layers3 className="size-4" /></div>)}</div><p>{disclaimer}</p><p className="text-muted-foreground">The full project still requires domain-adapted models, GeoTIFF parsing, real optical–SAR inputs, co-registration, and benchmark evaluation. This demonstration does not claim those capabilities or ISRO endorsement.</p></div>}
    {view === 'scenes' && <div className="scene-picker">{scenes.map(scene => <button key={scene.id} className="scene-option" aria-pressed={sceneId === scene.id} onClick={() => { onScene(scene.id); setView(null) }}><img src={scene.image} alt="" /><span><strong>{scene.name}</strong><small>{scene.subtitle}</small></span><ArrowRight className="size-4" /></button>)}</div>}
    {view === 'upload' && <div className="upload-content">{Array.from({ length: mode === 'single' ? 1 : 2 }, (_, slot) => <Field key={slot}><FieldLabel htmlFor={`upload-${slot}`}>{slot === 0 ? mode === 'temporal' ? 'Before image' : 'Optical image' : mode === 'temporal' ? 'After image' : 'SAR image (preview)'}</FieldLabel><div className="upload-slot"><Upload className="size-5 text-primary" /><input id={`upload-${slot}`} type="file" accept="image/png,image/jpeg" disabled={uploading} onChange={e => { const f = e.target.files?.[0]; if (f) onUpload(f, slot); e.target.value = '' }} /><small>{uploads[slot]?.name || 'PNG or JPEG · up to 10 MB'}</small></div></Field>)}{uploadError && <p className="text-destructive text-sm" role="alert">{uploadError}</p>}<p className="text-xs text-muted-foreground">TIFF/GeoTIFF is not supported in this demo. Use a PNG/JPEG preview. Paired uploads are not checked for geographic alignment.</p><Button onClick={() => setView(null)} disabled={uploading || !uploads[0]}>{uploading ? 'Validating image…' : 'Use image preview'}<ArrowRight data-icon="inline-end" /></Button></div>}
    {view === 'history' && <div className="history-list">{history.length ? history.map(r => <button key={r.id} onClick={() => { onRestore(r); setView(null) }}><div><span>{taskNames[r.task]}</span><small>{r.query}</small></div><ArrowRight className="size-4" /></button>) : <p>No analyses yet. Run a query to start your session history.</p>}</div>}
    {view === 'export' && result && <div className="export-options"><p className="text-sm text-muted-foreground">{disclaimer}</p><button onClick={() => downloadReport(result, 'html')}><FileText className="size-6 text-primary" /><span><strong>Analysis report</strong><small>Self-contained HTML · Print to save as PDF</small></span><ArrowDownToLine className="size-4" /></button><button onClick={() => downloadReport(result, 'json')}><FileCode2 className="size-6 text-primary" /><span><strong>Execution record</strong><small>JSON · Query, annotations, result & trace</small></span><ArrowDownToLine className="size-4" /></button></div>}
  </DialogContent></Dialog>
}
